version: '3.8'

services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "8080:80"     # HTTP
      - "8443:443"    # HTTPS
      - "8181:81"     # NPM Admin UI
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - npm-data:/data
      - npm-letsencrypt:/etc/letsencrypt
    networks:
      - proxy
  noip-updater:
    image: ghcr.io/noipcom/noip-duc:latest
    container_name: noip-updater
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - noip-data:/config
    networks:
      - proxy
  mediaflow_proxy:
    build: https://github.com/mhdzumair/mediaflow-proxy.git
    container_name: mediaflow_proxy
    env_file:
      - ./mfp/.env
    restart: unless-stopped
  mammamia:
    build: ./mammamia
    container_name: mammamia
    env_file:
      - ./mammamia/.env
    restart: unless-stopped 
  #stremio-docker:
  #  image: tsaridas/stremio-docker:latest
  #  container_name: stremio-docker
  #  ports:
  #    - "8080:8080"
  #    - "11470:11470"
  #  environment:
  #    - NO_CORS=1
  #    - CASTING_DISABLED=1
  #  restart: unless-stopped
  streamv:
    build: https://github.com/qwertyuiop8899/StreamV.git#main
    container_name: streamv
    env_file:
      - ./mammamia/.env
    restart: unless-stopped 
    command: pnpm start
  
  #webstreamr:
  #  build: https://github.com/webstreamr/webstreamr.git#main
  #  container_name: webstreamr
  #  restart: unless-stopped

volumes:
  npm-data:
  npm-letsencrypt:
  noip-data:

networks:
  proxy:
    external: true
